# Generated by Django 5.1.6 on 2025-03-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
            ],
        ),
    ]
