# Generated by Django 5.1.6 on 2025-03-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_alter_appuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='group',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
