# Generated by Django 5.1.6 on 2025-03-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0004_alter_appuser_options_remove_appuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='group',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups', related_name='custom_user_group', to='auth.group', verbose_name='groups'),
        ),
    ]
