# Generated by Django 5.1.6 on 2025-03-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_appuser_group_remove_appuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, default='IiBFD2AJ8aTVt6Wfep5E', max_length=50, null=True, unique=True),
        ),
    ]
