# Generated by Django 5.1.6 on 2025-03-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_appuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, default='0j6MIuQRaAwT4XpL5H9t', max_length=50, null=True, unique=True),
        ),
    ]
