# Generated by Django 5.1.6 on 2025-03-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_appuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, default='YHWoZuwsEj2LbO3Sd7v0', max_length=50, null=True, unique=True),
        ),
    ]
