# Generated by Django 5.1.6 on 2025-03-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_appuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, default='v2xrHLMVAkEcO1ojmtUR', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='workgroup',
            field=models.CharField(choices=[('C', 'Заказчик'), ('E', 'Исполнитель'), ('A', 'Администратор')], default='C', max_length=1),
        ),
    ]
