# Generated by Django 5.1.6 on 2025-03-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_appuser_username_alter_appuser_workgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechat',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, default='geE02TaN3VF1hlijkJ5m', max_length=50, null=True, unique=True),
        ),
    ]
