# Generated by Django 5.1.6 on 2025-03-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_messagechat_created_at_alter_appuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagechat',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, default='KW4kwvoZMla9XSVRt5Nu', max_length=50, null=True, unique=True),
        ),
    ]
