# Generated by Django 5.1.6 on 2025-03-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_appuser_last_name_alter_appuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, default='etXqxGFb7m3PZf8aO2Cw', max_length=50, null=True, unique=True),
        ),
    ]
