# Generated by Django 5.1.6 on 2025-03-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_appuser_last_name_alter_appuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, default='w43PXDHUkSWFgE2L7mrO', max_length=50, null=True, unique=True),
        ),
    ]
