# Generated by Django 5.1.6 on 2025-03-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_messagechat_options_alter_appuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagechat',
            options={'ordering': ['sended_at']},
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, default='NWSXxaiYvqe7Ezd48L9H', max_length=50, null=True, unique=True),
        ),
    ]
