# Generated by Django 5.1.6 on 2025-03-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_messagechat_options_alter_appuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, default='FqjK9I8eXiEm2g7toOB6', max_length=50, null=True, unique=True),
        ),
    ]
