# Generated by Django 5.1.6 on 2025-03-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_appuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, default='ABa1pITR5KWzy4Shu9iF', max_length=50, null=True, unique=True),
        ),
    ]
